# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

 target 'YJApiRequestTool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YJApiRequestTool

  pod 'AFNetworking', '~> 3.2.1'
  pod 'MJExtension', '~> 3.0.15.1'

  
  target 'YJApiRequestToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJApiRequestToolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
